// Web/src/components/Call.tsx
import React, { useState } from "react";
import "./Call.css";


const Call = ({account, onCall}) => {
  const [invitee, setInvitee] = useState("");
  const [callType, setCallType] = useState(2); // 2: 视频呼叫, 1: 音频呼叫

  const handleCallTypeChange = (e) => {
    setCallType(Number(e.target.value));
  };

  const call = () => {
    if (!invitee) {
      alert("请输入账号ID");
      return;
    }
    if (account === invitee) {
      alert("不能呼叫自己");
      return;
    }
    try {
      onCall(invitee.trim(), callType);
    } catch (error) {
      console.error("call error: ", error);
    }
  };

  return (
    <div className="call-container">
      <div
        style={{
          flex: "auto",
          display: "flex",
          flexDirection: "column",
          padding: "0 10px",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            padding: "10px 0",
            color: "#1f1f26",
          }}
        >
          <label>您的ID</label>
          <div style={{ marginLeft: "10px" }}>{account}</div>
        </div>

        <div className="search">
          <div className="call-input-box">
            <input
              className="input-search-user"
              type="text"
              value={invitee}
              maxLength={50}
              placeholder="请输入账号ID"
              onChange={(e) => setInvitee(e.target.value)}
            />
          </div>
          <div className="btn-search" onClick={call}>
            呼叫
          </div>
        </div>

        <div
          style={{
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            color: "#1f1f26",
            padding: "10px 0",
          }}
        >
          <div>呼叫类型</div>
          <div
            style={{
              marginLeft: "15px",
              display: "flex",
              flexDirection: "row",
              alignItems: "center",
            }}
          >
            <label
              style={{
                display: "flex",
                flexDirection: "row",
                alignItems: "center",
              }}
            >
              <input
                type="radio"
                value={2}
                checked={callType === 2}
                onChange={handleCallTypeChange}
              />
              <span style={{ marginLeft: "5px" }}>视频呼叫</span>
            </label>
            <label
              style={{
                marginLeft: "15px",
                display: "flex",
                flexDirection: "row",
                alignItems: "center",
              }}
            >
              <input
                type="radio"
                value={1}
                checked={callType === 1}
                onChange={handleCallTypeChange}
              />
              <span style={{ marginLeft: "5px" }}>音频呼叫</span>
            </label>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Call;

// Web/basic-vue3/src/components/Call.vue
<template>
  <div class="call-container">
    <div>
      <div
        style="
          display: flex;
          align-items: center;
          padding: 10px 0;
          color: #1f1f26;
        "
      >
        <label>您的ID</label>
        <div style="margin-left: 10px">{{ account }}</div>
      </div>

      <div class="call-section-title">一对一通话</div>
      <div class="search">
        <div class="call-input-box">
          <input
            v-model.trim="invitee"
            class="input-search-user"
            type="text"
            maxlength="50"
            placeholder="请输入账号ID"
          />
        </div>
        <div class="btn-search" @click="startCall">呼叫</div>
      </div>

      <div class="call-radio-row">
        <div>呼叫类型</div>
        <div class="call-radio-group">
          <label class="call-radio-label">
            <input v-model="callType" type="radio" :value="2" />
            <span>视频呼叫</span>
          </label>
          <label class="call-radio-label">
            <input v-model="callType" type="radio" :value="1" />
            <span>音频呼叫</span>
          </label>
        </div>
      </div>
    </div>

    <div class="call-divider" />

    <div>
      <div class="call-section-title">群组通话</div>
      <div class="search">
        <div class="call-input-box">
          <input
            v-model.trim="groupMembers"
            class="input-search-user"
            type="text"
            maxlength="200"
            placeholder="多个账号用英文逗号分隔"
          />
        </div>
        <div class="btn-search" @click="startGroupCall">发起群呼</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import './Call.css'

const props = defineProps<{
  account: string
}>()

const emit = defineEmits<{
  (event: 'call', invitee: string, callType: number): void
  (event: 'group-call', members: string[], callType: number): void
}>()

const invitee = ref('')
const groupMembers = ref('')
const callType = ref(2)

function startCall(): void {
  if (!invitee.value) {
    window.alert('请输入账号ID')
    return
  }

  if (props.account === invitee.value) {
    window.alert('不能呼叫自己')
    return
  }

  emit('call', invitee.value, callType.value)
}

function startGroupCall(): void {
  const members = groupMembers.value
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean)
    .filter((item) => item !== props.account)

  if (members.length === 0) {
    window.alert('请至少输入一个被叫账号')
    return
  }

  emit('group-call', members, callType.value)
}
</script>
